default_platform(:ios)

# TestFlight
# development
platform :ios do
  desc "Upload a new development build to TestFlight"
  lane :testflightdev do
    increment_build_number(xcodeproj: "myday.xcodeproj")
    build_app(workspace: "myday.xcworkspace", scheme: "myday Debug")
    upload_to_testflight
  end
end

# production
platform :ios do
  desc "Upload a new production build to TestFlight"
  lane :testflightprod do
    increment_build_number(xcodeproj: "myday.xcodeproj")
    build_app(workspace: "myday.xcworkspace", scheme: "myday Release")
    upload_to_testflight
  end
end


# Firebase App Distribution
# development
platform :ios do
  desc "Upload a new development build to Firebase App Distribution"
  lane :firebasedev do
    increment_build_number(xcodeproj: "myday.xcodeproj")
    build_app(workspace: "myday.xcworkspace", scheme: "myday Debug")
    firebase_app_distribution(
      groups: "engineering",
      release_notes: "Fastlane upload."
    )
  end
end

# production
platform :ios do
  desc "Upload a new production build to Firebase App Distribution"
  lane :firebaseprod do
    increment_build_number(xcodeproj: "myday.xcodeproj")
    build_app(workspace: "myday.xcworkspace", scheme: "myday Release")
    firebase_app_distribution(
      groups: "engineering",
      release_notes: "Fastlane upload."
    )
  end
end